title: Ting Wang's Homepage
page-top-title: Ting Wang
top-section-bg-text: Computer Science in Artificial Intelligence
home-subtitle: Ting Wang&ensp;|&ensp;王霆
copyright-text: '&copy; Ting Wang 2025-2028. All Rights Reserved.'
